// Phase 0.5 MVP — hand-curated weird Amazon products. No DB, no API yet.
// 25 items chosen for the "WTF" reveal moment (per Joe's vision in
// vault/kai/projects/pricetag-amazon-game.md).
//
// Prices are real (or close to it) as of 2026 listings; the game's whole
// premise is that you wouldn't predict them. Photos point at placeholder
// Unsplash images standing in for the eventual mirrored Amazon photos.

export type AmazonProduct = {
  id: string;
  // Pre-reveal copy — what the player sees while guessing. Brand-stripped,
  // model-number-stripped, but still descriptive.
  displayTitle: string;
  category: string; // vibe tier — "What Even Is This?", etc.
  blurb: string;   // 1-2 sentences, no spoilers
  // Post-reveal — full title, brand, ASIN, price.
  fullTitle: string;
  brand: string;
  asin: string;
  priceUsd: number;
  // Photos — Unsplash placeholders for now.
  photos: string[];
  // UI accent if photos fail to load.
  bandColor: string;
  // Soft signals for the reveal screen — pulled from real Amazon-ish data.
  rating?: number;
  reviewCount?: number;
  badge?: string;
};

// Vibe tiers double as our weirdness category. See plan doc Addendum.
export const TIERS = [
  "What Even Is This?",
  "Why Does This Cost That?",
  "TikTok Made Me Buy It",
  "Tactically Weird",
  "Suspiciously Cheap",
  "Suspiciously Expensive",
] as const;

export const PRODUCTS: AmazonProduct[] = [
  {
    id: "duck-lamp",
    displayTitle: "Ceramic Duck Lamp With Existential Slogan",
    category: "TikTok Made Me Buy It",
    blurb: "Ceramic duck lamp. The lampshade reads a single existential phrase.",
    fullTitle: "Existential Crisis Duck Lamp",
    brand: "Goose Creative",
    asin: "B0CGXKLM23",
    priceUsd: 45,
    photos: ["https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=1600&q=80"],
    bandColor: "#F5D547",
    rating: 4.7, reviewCount: 1820, badge: "Amazon's Choice",
  },
  {
    id: "cage-pillow",
    displayTitle: "Reversible-Sequin Decorative Pillow Featuring An Actor's Face",
    category: "Tactically Weird",
    blurb: "Brush the sequins one way to see a neutral pattern, the other to reveal a celebrity portrait.",
    fullTitle: "Nicolas Cage Reversible Sequin Pillow Cover",
    brand: "MagicPillow",
    asin: "B07X1ZK8YQ",
    priceUsd: 23,
    photos: ["https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=1600&q=80"],
    bandColor: "#C0A2DC",
    rating: 4.6, reviewCount: 5210,
  },
  {
    id: "dino-nuggie-plush",
    displayTitle: "Giant Plush Pillow Shaped Like A Dinosaur-Shaped Chicken Nugget",
    category: "TikTok Made Me Buy It",
    blurb: "A pillow shaped exactly like a single dinosaur chicken nugget, scaled up to body-pillow size.",
    fullTitle: "Dino Nuggies Body Pillow Plush 30-inch",
    brand: "iScream",
    asin: "B0BQR4F7W2",
    priceUsd: 45,
    photos: ["https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1600&q=80"],
    bandColor: "#E89B45",
    rating: 4.8, reviewCount: 8730, badge: "#1 Best Seller",
  },
  {
    id: "trex-costume",
    displayTitle: "Adult-Sized Inflatable Dinosaur Costume",
    category: "What Even Is This?",
    blurb: "Full-body inflatable. Built-in fan. You become a T-Rex.",
    fullTitle: "Rhynay Inflatable T-Rex Halloween Costume",
    brand: "Rhynay",
    asin: "B07K1MZQXY",
    priceUsd: 49,
    photos: ["https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1600&q=80"],
    bandColor: "#7CB342",
    rating: 4.5, reviewCount: 22100,
  },
  {
    id: "giant-gummy",
    displayTitle: "Single Edible Bear-Shaped Confection, 5 Pounds",
    category: "Why Does This Cost That?",
    blurb: "Yes, one piece of candy. Yes, it weighs five pounds.",
    fullTitle: "Vat19 World's Largest Gummy Bear (5 lbs)",
    brand: "Vat19",
    asin: "B003A7HJWS",
    priceUsd: 30,
    photos: ["https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=1600&q=80"],
    bandColor: "#E53E3E",
    rating: 4.3, reviewCount: 14502,
  },
  {
    id: "bob-ross-chia",
    displayTitle: "Painter-Bust Chia Pet Pottery Kit",
    category: "Tactically Weird",
    blurb: "Add water, watch chia seeds sprout the hair of a famous television painter.",
    fullTitle: "Chia Pet Bob Ross with Seed Pack",
    brand: "Chia Pet",
    asin: "B07JGPHKMK",
    priceUsd: 20,
    photos: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1600&q=80"],
    bandColor: "#34A89A",
    rating: 4.7, reviewCount: 9300,
  },
  {
    id: "yodeling-pickle",
    displayTitle: "Battery-Powered Yodeling Pickle (Plastic, Not Edible)",
    category: "What Even Is This?",
    blurb: "Press the button. The pickle yodels.",
    fullTitle: "Accoutrements Yodelling Pickle",
    brand: "Accoutrements",
    asin: "B0036YL0H6",
    priceUsd: 15,
    photos: ["https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1600&q=80"],
    bandColor: "#4CAF50",
    rating: 4.5, reviewCount: 3120,
  },
  {
    id: "billy-bass",
    displayTitle: "Wall-Mounted Fish That Sings",
    category: "Tactically Weird",
    blurb: "Motion-activated singing fish you mount on the wall like a hunting trophy.",
    fullTitle: "Big Mouth Billy Bass Singing Fish",
    brand: "Gemmy",
    asin: "B0001ZMU1G",
    priceUsd: 50,
    photos: ["https://images.unsplash.com/photo-1545816250-e12bedba42ba?w=1600&q=80"],
    bandColor: "#1E88E5",
    rating: 4.5, reviewCount: 22020, badge: "Amazon's Choice",
  },
  {
    id: "weighted-frog",
    displayTitle: "Heavy Emotional Support Frog Plush, 3.5 Pounds",
    category: "Why Does This Cost That?",
    blurb: "A weighted frog plush. Marketing material is unironic.",
    fullTitle: "MorisMos Heavy Emotional Support Frog Weighted Plush",
    brand: "MorisMos",
    asin: "B0BTK5K8MR",
    priceUsd: 60,
    photos: ["https://images.unsplash.com/photo-1597762111678-a3afa0d8c4cb?w=1600&q=80"],
    bandColor: "#7CB342",
    rating: 4.9, reviewCount: 4520, badge: "Amazon's Choice",
  },
  {
    id: "tortilla-blanket",
    displayTitle: "Circular Soft Blanket Printed To Look Like A Flour Tortilla",
    category: "TikTok Made Me Buy It",
    blurb: "Round, soft, photorealistic flour tortilla. You wrap yourself in it like a burrito.",
    fullTitle: "BlanQuil Tortilla Blanket 60-inch",
    brand: "BlanQuil",
    asin: "B07XBN5L9Q",
    priceUsd: 25,
    photos: ["https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1600&q=80"],
    bandColor: "#D4A968",
    rating: 4.6, reviewCount: 18280, badge: "#1 Best Seller",
  },
  {
    id: "squatty-potty",
    displayTitle: "Plastic Stool For Use In The Bathroom",
    category: "Why Does This Cost That?",
    blurb: "It is what it sounds like. The marketing materials famously involved a cartoon unicorn.",
    fullTitle: "Squatty Potty The Original Bathroom Toilet Stool",
    brand: "Squatty Potty",
    asin: "B00B40OFTU",
    priceUsd: 30,
    photos: ["https://images.unsplash.com/photo-1603417406253-4c65c06974c2?w=1600&q=80"],
    bandColor: "#F5F5F5",
    rating: 4.6, reviewCount: 87320, badge: "#1 Best Seller",
  },
  {
    id: "hairy-saddle",
    displayTitle: "Furry Cover That Fits Over A Bicycle Seat",
    category: "What Even Is This?",
    blurb: "Long-haired plush cover for a standard bike saddle. Color: brown. Purpose: unclear.",
    fullTitle: "Furry Bicycle Saddle Cover (Long-Hair Brown)",
    brand: "FurZilla",
    asin: "B083K2P5Q9",
    priceUsd: 28,
    photos: ["https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=1600&q=80"],
    bandColor: "#8B4513",
    rating: 4.2, reviewCount: 880,
  },
  {
    id: "polaroid-fridge",
    displayTitle: "Personal Mini-Fridge Shaped Like A Vintage Instant Camera",
    category: "Suspiciously Expensive",
    blurb: "Holds 6 cans. Looks like a giant Polaroid camera. Plugs into a wall.",
    fullTitle: "Polaroid PRF064PCV Mini Cooler Compact Fridge",
    brand: "Polaroid",
    asin: "B09MV7P9Z3",
    priceUsd: 119,
    photos: ["https://images.unsplash.com/photo-1606800052052-a08af7148866?w=1600&q=80"],
    bandColor: "#FF6F61",
    rating: 4.5, reviewCount: 1480,
  },
  {
    id: "toast-pillow",
    displayTitle: "Body Pillow Printed To Look Like A Slice Of Buttered Toast",
    category: "TikTok Made Me Buy It",
    blurb: "Photorealistic toast print on a soft body pillow. Comes with cartoon butter stick.",
    fullTitle: "Throwboy Toast Throw Pillow Set",
    brand: "Throwboy",
    asin: "B07Z4N1XK5",
    priceUsd: 50,
    photos: ["https://images.unsplash.com/photo-1481072028516-4d59ba80df95?w=1600&q=80"],
    bandColor: "#D4A968",
    rating: 4.7, reviewCount: 3120,
  },
  {
    id: "hot-dog-costume",
    displayTitle: "Adult Inflatable Costume Of A Sausage In A Bun",
    category: "What Even Is This?",
    blurb: "Self-inflating. Built-in fan. You walk around as a hot dog.",
    fullTitle: "Spooktacular Creations Inflatable Hot Dog Costume",
    brand: "Spooktacular Creations",
    asin: "B07GG1L5MY",
    priceUsd: 30,
    photos: ["https://images.unsplash.com/photo-1572448862527-d3c904757de6?w=1600&q=80"],
    bandColor: "#E53E3E",
    rating: 4.4, reviewCount: 6020,
  },
  {
    id: "rubber-chicken-doorbell",
    displayTitle: "Wireless Doorbell That Plays A Rubber-Chicken Squawk",
    category: "What Even Is This?",
    blurb: "Doorbell. When pressed, squawks like the squeaky rubber chicken toy.",
    fullTitle: "Chickbell Wireless Rubber Chicken Doorbell",
    brand: "Chickbell",
    asin: "B091HRGT2X",
    priceUsd: 24,
    photos: ["https://images.unsplash.com/photo-1582719188393-bb71ca45dbb9?w=1600&q=80"],
    bandColor: "#FFD66B",
    rating: 4.3, reviewCount: 510,
  },
  {
    id: "octopus-hat",
    displayTitle: "Knit Beanie With Eight Posable Tentacle Limbs",
    category: "Tactically Weird",
    blurb: "Beanie. 8 stuffed tentacles dangle off the sides. Each tentacle bends.",
    fullTitle: "Tentacle Hat Octopus Knit Beanie with Posable Limbs",
    brand: "TentacleHat",
    asin: "B07R9PT8DK",
    priceUsd: 32,
    photos: ["https://images.unsplash.com/photo-1530219583926-58cb1d0c8f0d?w=1600&q=80"],
    bandColor: "#9C27B0",
    rating: 4.5, reviewCount: 6210,
  },
  {
    id: "honey-bear-ring",
    displayTitle: "Translucent Plastic Bear Functioning As A Ring Display",
    category: "Suspiciously Cheap",
    blurb: "Honey-bear-shaped figure. Hands extend forward. Rings stack on hands.",
    fullTitle: "Honey Bear Ring Holder Jewelry Display",
    brand: "FCTRY",
    asin: "B07KN3X3WY",
    priceUsd: 15,
    photos: ["https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=1600&q=80"],
    bandColor: "#D4A968",
    rating: 4.7, reviewCount: 980,
  },
  {
    id: "bigfoot-statue",
    displayTitle: "Outdoor Garden Statue Of A Large Cryptid Walking",
    category: "Why Does This Cost That?",
    blurb: "Hand-painted resin statue, 24 inches. Sasquatch mid-stride.",
    fullTitle: "Design Toscano Bigfoot the Garden Yeti Statue",
    brand: "Design Toscano",
    asin: "B00HZ3R6AK",
    priceUsd: 65,
    photos: ["https://images.unsplash.com/photo-1530056790638-c6037e44a7e2?w=1600&q=80"],
    bandColor: "#5D4037",
    rating: 4.7, reviewCount: 1240,
  },
  {
    id: "cat-cave",
    displayTitle: "Hand-Felted Wool Dome-Shaped Bed For A Pet",
    category: "Suspiciously Expensive",
    blurb: "Felt wool dome with a single circular opening. Made by hand. Cats may or may not use.",
    fullTitle: "Meowfia Premium Felt Cat Cave (Large)",
    brand: "Meowfia",
    asin: "B017PUMM3Y",
    priceUsd: 80,
    photos: ["https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=1600&q=80"],
    bandColor: "#9E9E9E",
    rating: 4.6, reviewCount: 14210, badge: "Amazon's Choice",
  },
  {
    id: "foot-warmer",
    displayTitle: "Plush Footwear That Plugs Into A USB Port To Generate Heat",
    category: "What Even Is This?",
    blurb: "Slipper-shape. You plug the cord into your laptop. Feet get warm.",
    fullTitle: "ObboMed USB Heated Slippers Plush Feet Warmer",
    brand: "ObboMed",
    asin: "B074HHX1QB",
    priceUsd: 27,
    photos: ["https://images.unsplash.com/photo-1542838132-92c53300491e?w=1600&q=80"],
    bandColor: "#FF6F61",
    rating: 4.1, reviewCount: 920,
  },
  {
    id: "mustache-pacifier",
    displayTitle: "Infant Pacifier Molded To Look Like A Curled Mustache",
    category: "Suspiciously Cheap",
    blurb: "Standard silicone pacifier. The shield is shaped like a handlebar mustache.",
    fullTitle: "Mustachifier The Gentleman Mustache Pacifier",
    brand: "Mustachifier",
    asin: "B005GNQA1Y",
    priceUsd: 8,
    photos: ["https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=1600&q=80"],
    bandColor: "#5D4037",
    rating: 4.4, reviewCount: 3220,
  },
  {
    id: "wine-glass-holder",
    displayTitle: "Wearable Necklace That Cradles A Filled Wine Glass",
    category: "Tactically Weird",
    blurb: "Loop of cord with a holder. Wear it. Put your wine glass in it. Walk hands-free.",
    fullTitle: "GoVino Wine Glass Necklace Hands-Free Drink Holder",
    brand: "GoVino",
    asin: "B07T2BR2HC",
    priceUsd: 16,
    photos: ["https://images.unsplash.com/photo-1510630203036-fff3acd1c98c?w=1600&q=80"],
    bandColor: "#7B1FA2",
    rating: 4.2, reviewCount: 470,
  },
  {
    id: "toilet-paper-wedding",
    displayTitle: "Kit For Building A Wedding Dress Entirely Out Of Toilet Paper",
    category: "Suspiciously Cheap",
    blurb: "Includes tape, ribbon, instructions. Bring your own toilet paper. For bachelorette parties.",
    fullTitle: "TP Wedding Dress Toilet Paper Bridal Shower Game Kit",
    brand: "Big Mouth Toys",
    asin: "B07ZRQ8M5P",
    priceUsd: 18,
    photos: ["https://images.unsplash.com/photo-1517446915321-7b9b6abc89c8?w=1600&q=80"],
    bandColor: "#F5F5F5",
    rating: 4.3, reviewCount: 230,
  },
  {
    id: "gorilla-couch",
    displayTitle: "Oversized Sculpted Lounge Furniture In The Shape Of A Sitting Primate",
    category: "Suspiciously Expensive",
    blurb: "8 feet tall. The seat is the lap. Hand-sculpted, foam-filled, upholstered. Viral on social media.",
    fullTitle: "Custom Gorilla Lounge Chair 8-ft Hand-Sculpted",
    brand: "WildBeast Furniture",
    asin: "B0CR3K9MP1",
    priceUsd: 2400,
    photos: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1600&q=80"],
    bandColor: "#3E2723",
    rating: 4.8, reviewCount: 92,
  },
];

// Stable shuffle by id-hash so different sessions get different orderings
// without ever showing the same product twice in a single run.
export function shuffleDeck(seed = Date.now()): AmazonProduct[] {
  const arr = [...PRODUCTS];
  let s = seed % 2147483647;
  for (let i = arr.length - 1; i > 0; i--) {
    s = (s * 16807) % 2147483647;
    const j = s % (i + 1);
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
